version: '3.9'
services:
  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: 1234
                POSTGRES_DB: orders
    ports:
        - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: passw
      PGADMIN_LISTEN_PORT: 85
    ports:
        - "8085:85"    